### ISSUE TITLE
/deployments endpoint POST method 500 error

### ISSUE THREAD

**Issue by pedbermar** [eclipse-researchlabs/smartclide-db-api#17] opened 2023-01-18 13:03 UTC
I´m getting a 500 error with the following request:

```
curl -X POST \
  'https://api.dev.smartclide.eu/smartclide-db/deployments' \
  --header 'Accept: */*' \
  --header 'User-Agent: Thunder Client (https://www.thunderclient.com)' \
  --header 'Authorization: Bearer <YOUR_TOKEN_HERE > ' \
  --header 'Content-Type: application/json' \
  --data-raw '{
  "id": "2f586e4c-32dc-4395-921a-dd1daf447ed6",
  "user": "pberrocal",
  "name": "Wellness Challenge",
  "user_id": "628c87f6aa5a2857398a80a0",
  "project": "wellness_challenge",
  "git_credentials_id": "628c922780b42501489a85dd",
  "workflow_id": "628c933891b53612590a96de",
  "service_id": "628c928d80b42501489a85de",
  "service_url": "http://20.166.216.212:6543",
  "port": 6543,
  "replicas": 1,
  "state": "active",
  "k8s_url": "https://smartclide-dns-99f66729.hcp.northeurope.azmk8s.io:443",
  "created_at": "2023-01-18T11:27:32.480183"
}'
```
Response was:
```
{
  "timestamp": "2023-01-18T12:49:38.092+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "path": "/deployments"
}
```

Can someone try to reproduce and see what's in the service error log?

Thank you

**Comment by reimer-atb** [comment] 2023-01-19 10:52
```
javax.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint 'javax.validation.constraints.NotEmpty' validating type 'java.lang.Integer'. Check configuration for 'port'
```

Probably caused by `org.eclipse.opensmartclide.dbapi.model.Deployment#port`?

```
    @NotEmpty
    private Integer port;
```

According to the docs for `NotEmpty`:

> Supported types are:
> - CharSequence (length of character sequence is evaluated)
> - Collection (collection size is evaluated)
> - Map (map size is evaluated)
> - Array (array length is evaluated)

You should use `@NotNull` and `@Min`, `@Max` instead.

**Comment by deanone** [comment] 2023-01-24 08:39
@pedbermar @philipreimer I just made a PR (#19) with a quick fix for this bug.

@philipreimer can you please review it?

**Closed as completed** 2023-01-24 09:14 UTC
